# Site settings
title: Terrill Dent
email: your-email@domain.com
name: Terrill Dent
description: > #
  The personal website of <a href=
  "/">Terrill Dent</a>, a software developer in Waterloo Ontario.
baseurl: ""
destination: "../build/"
url: "http://www.terrill.ca"
twitter_username: terrilldent

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]
